### ISSUE TITLE
 using '*' to highlight, easymotion can not move to next word

### ISSUE THREAD

**Issue by gansteed** [Lokaltog/vim-easymotion#196]
my easymotion binding:

```viml
" ================ Easymotion
let g:EasyMotion_leader_key = 'f'
" Gif config
map  / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)
```

**Comment by llfm** [comment]
The maps:
```vim
map  n <Plug>(easymotion-next)
map  N <Plug>(easymotion-prev)
```
Are really really nice. It's a shame that it's conflicts with */#.
I could map the options to another word to use the default behavior of n/N (more maps seems bad), but it would be handy if easymotion could just handle it or degrade to the default behavior of vim.
I really don't know the effort to make any of this, or if it worth.

**Comment by drobati** [comment]
Just ran into this today. Guess I'll removoe the maps.

**Comment by haya14busa** [comment]
If you want to integrate with incremental search feature and default search, I recommend to use https://github.com/haya14busa/incsearch.vim.

If you miss easymotion's feature, please try this configuration https://github.com/Lokaltog/vim-easymotion/issues/146#issuecomment-75443473
