### ISSUE TITLE
Binding s for operator motions conflict with surround.vim

### ISSUE THREAD

**Issue by jeosadn** [Lokaltog/vim-easymotion#204]
I'm not sure if this is an issue related to easymotion directly, but here is what I'm trying to do: I want to use s for easymotion-s2 in all contexts, so: s<2keys> jumps me to the target, vs<2keys> visually selects to the target, and <operator>s<2keys> does the operator to the target (yank, change, delete, etc)
 The mapping for visual mode and for normal mode work correctly, but for operator it does not seem to trigger. With showcmd on, typing ysaa displays, after each keypress: y -> s -> g@a -> nothing

Easymotion options on my vimrc:

    let g:EasyMotion_do_mapping = 0
    nmap s <Plug>(easymotion-s2)
    omap s <Plug>(easymotion-s2)
    vmap s <Plug>(easymotion-s2)
    map <Leader>j <Plug>(easymotion-j)
    map <Leader>k <Plug>(easymotion-k)
    let g:EasyMotion_smartcase = 1
    let g:EasyMotion_use_upper = 1
    let g:EasyMotion_use_smartsign_us = 1

Output of :map s

    v  s             <Plug>(easymotion-s2)
    o  s             <Plug>(easymotion-s2)
    n  s             <Plug>(easymotion-s2)

The issue seems to be only when using s as the map key, when I tried to use t it worked as expected.

**Comment by dani-h** [comment]
@haya14busa I've been looking for this everywhere, I was wondering why my s couldn't be used together with an action. You should stick it in README.md as both plugins are pretty popular.

**Comment by haya14busa** [comment]
Hmm... I did not recommend `map s <Plug>(easymotion-s2)` mapping at the first place.
Lots of example in README and help doc use `nmap` and `vmap`.

**Comment by dani-h** [comment]
Does it still conflict with vim surround with nmap and vmap?

**Comment by haya14busa** [comment]
I guess there are no conflict with `nmap` and `vmap`.
Please correct me if not.

**Comment by haya14busa** [comment]
Seems it's closable.
Please reopen if not or pull-requests are always welcome.

**Comment by dani-h** [comment]
I removed vim-surround and I'm too lazy to try it out, so yeah it can be closed.
