### ISSUE TITLE
easymotion-bd-t2 jumps to the character after target when the target is before cursor position

### ISSUE THREAD

**Issue by NicholasTD07** [Lokaltog/vim-easymotion#208]
For example I have following two lines in vim and my cursor is on that '-' character before 's2'

``` 
nmap s <Plug>(easymotion-<cursor>s2)
nmap t <Plug>(easymotion-bd-t2)
```

When I type 'tea', it shows that there are two targets. In the first line, target is 's' after 'ea' in the word 'easymothion'. In the second line, it is '(' before 'ea'.

But, shouldn't it show both targets before the targeted 'ea'?
In this case, the target in the first line should be '(' before 'ea'.

PS.
Great work! Love this plugin a lot. :D

Thanks!

**Comment by haya14busa** [comment]
The current behavior is expected.
I consider `<Plug>(easymotion-bd-t2)` as a motion which combine `<Plug>(easymotion-t2)` and `<Plug>(easymotion-T2)`.

> Great work! Love this plugin a lot. :D

Good to hear, thanks! :sparkles:
