### ISSUE TITLE
easymotion-dotrepeat and indentation operator ('>', '<')

### ISSUE THREAD

**Issue by WscriChy** [Lokaltog/vim-easymotion#211]
I have a map

  map . <Plug>(easymotion-dotrepeat)

When I press '<' or '>' and try to repeat it with '.' it does not work, 'Previous motion doesn't exist' is returned.

**Comment by haya14busa** [comment]
You should not map `.` to ` <Plug>(easymotion-dotrepeat)`. This mapping is used in the plugin and the users should not touch it. Please read `:h easymotion-dotrepeat`.

**Comment by WscriChy** [comment]
Ok, thank you, it also required to update the tpope-repeat to the latest version.
