### ISSUE TITLE
\f not working after installation(using vim addon manager)

### ISSUE THREAD

**Issue by waivek** [Lokaltog/vim-easymotion#213]
Hi. I installed EasyMotion with VAM. <Leader><Leader>w, b etc. work properly. However in search commands like <Leader><Leader>f, I get the error E605: 
![capture](https://cloud.githubusercontent.com/assets/5134623/6327949/e7a2c806-bb87-11e4-8a59-47b5fa163579.PNG)
Is there any workaround?

**Comment by haya14busa** [comment]
I guess it fixed with #171.

Please update vim-easymotion.

**Comment by waivek** [comment]
It's fixed! Thanks!
