### ISSUE TITLE
Colemak keyboard layout,  change key,  confusion

### ISSUE THREAD

**Issue by SmilePlz** [Lokaltog/vim-easymotion#217]
hi, thank you for easymotion.
I use colemak, and change key with "j" to "n" and other NJ,JN,ek,ke,EK,KE,yl,ly,YL,LY.
if use set langmap=nj,jn,NJ,JN,ek,ke,EK,KE,yl,ly,YL,LY the easymotion does not work. that is why I use jooize/vim-colemak. The easymotion not sees change key. When I click the "e" (up), he understands how key "k". how to fix it?

**Comment by haya14busa** [comment]
> and change key with "j" to "n" and other NJ,JN,ek,ke,EK,KE,yl,ly,YL,LY.

I didn't get it. `change key` means `noremap` ?

**Comment by SmilePlz** [comment]
I'm sorry that did not answer for a long time. Yes, I used noremap.
Here are some of my settings:
nnoremap n gj|xnoremap n gj|onoremap n gj|
nnoremap e gk|xnoremap e gk|onoremap e gk|
nnoremap y l|xnoremap y l|onoremap y l|

nnoremap e k|xnoremap e k|onoremap e k|
nnoremap n j|xnoremap n j|onoremap n j|

nnoremap k e|xnoremap k e|onoremap k e|
nnoremap K E|xnoremap K E|onoremap K E|

**Comment by SmilePlz** [comment]
and if I change:
map <Leader>n <Plug>(easymotion-eol-j) 
map <Leader>e <Plug>(easymotion-eol-k)
map <Leader>k <Plug>(easymotion-iskeyword-e)
does not work
