### ISSUE TITLE
hard to read characters highlighted with color similar as background color?

### ISSUE THREAD

**Issue by hatelove85911** [Lokaltog/vim-easymotion#218]
I'm using solarized theme,  below is a screenshot when I press <leader><leader>w, as you can see some keys are hard to read. I don't understand why some are in red but the others are in yellow.
![easy_motion](https://cloud.githubusercontent.com/assets/2359121/6894556/79cb5468-d709-11e4-9ec4-5a5698b7478c.png)

**Comment by haya14busa** [comment]
See `:h easymotion-custom-hl`

Yellow is for target which requires more than one characters.
