### ISSUE TITLE
Make easymotion-next/easymotion-prev work with whole word search (*)

### ISSUE THREAD

**Issue by srushti** [Lokaltog/vim-easymotion#219]
Doing a search with `*` (whole word under cursor `:help *`), sets the `"/` register, and generally `n`/`N` works normally. But `easymotion-next`/`easymotion-prev` goes back to using the last text explicitly searched by `easymotion-sn`. It would be nice if it picked up `*` searches too.

**Comment by haya14busa** [comment]
easymotion-next/prev should use only history of easymotion. So I have no plan to support it.

I recommend to use https://github.com/haya14busa/incsearch.vim and collaborate with easymotion like this https://github.com/Lokaltog/vim-easymotion/issues/146#issuecomment-75443473
