### ISSUE TITLE
<Plug>(easymotion-sn) not finding folded text

### ISSUE THREAD

**Issue by dan-silva** [Lokaltog/vim-easymotion#223]
Well, first of all, I know that this option is not documented by now, but I found no other way to solve my initial problem (explained below).

When searching with `<Plug>(easymotion-sn)` with `g:EasyMotion_skipfoldedline = 0`, the matching text inside a fold is not being focused (although when tabbing between the screens the fold region **is** focused). The fold will be expanded only after a `<Plug>(easymotion-next)` or `<Plug>(easymotion-prev)` just as the default Vim behaviour.

It would be great if the folds were expanded, instead of echoing `EasyMotion: No matches` as it actually found it in some way.

**Comment by haya14busa** [comment]
If there are hundreds of lines in folds, it's performance will be incredibly down, and If there also are target character on lines after fold line, we cannot show both result simultaneously. It will be a inconsistent behavior. 

So I don't want to implement it.

There are option named `:h <Over>(em-openallfold)` which open all fold when searching. I guess it helps this problem.
