### ISSUE TITLE
Slow start time when first triggering easymotion-s

### ISSUE THREAD

**Issue by amosbird** [Lokaltog/vim-easymotion#225]
I've experienced about 5 seconds delay when making first call to easymotion-s. After that, it works smoothly. I'm using nightly neovim on CentOS 7. The file size I'm editing is small.

**Comment by haya14busa** [comment]
duplicate #136

**Comment by haya14busa** [comment]
@amosbird Could you please trying this https://github.com/Lokaltog/vim-easymotion/issues/136#issuecomment-39433991 ?
