### ISSUE TITLE
Supporting operator pending mode?

### ISSUE THREAD

**Issue by ThomsonTan** [Lokaltog/vim-easymotion#226]
Seems all easy motions don't support operator pending mode. Could it be supported?

**Comment by haya14busa** [comment]
EasyMotion already support operator pending mode including dot repeat. I guess your configuration is something wrong

**Comment by ThomsonTan** [comment]
Thanks. What's the configuration need to enable easymotion-s2 work in operator pending mode? I mapped this funciton to 's', and it works well except to used as motion for operators.

**Comment by haya14busa** [comment]
`:omap <Plug>(easymotion-s2)`  and make sure this does not conflict with surround.vim or some other plugins

**Comment by ThomsonTan** [comment]
That's right, I missed this :omap. Thanks
