### ISSUE TITLE
Can I change character color?

### ISSUE THREAD

**Issue by chan15** [Lokaltog/vim-easymotion#229]
![](http://i.imgur.com/P9tzwOb.png)

Ubuntu 14
vim 7.4
colorscheme [PaperColor](https://github.com/NLKNguyen/papercolor-theme)

The color is too dazzling to pick, but normal in Windows environment, any solution to fix it?

**Comment by chan15** [comment]
Sorry, I found it's xshell's issue, never mind it

**Comment by haya14busa** [comment]
You can change character color. See https://github.com/Lokaltog/vim-easymotion/blob/9f1c449edfce6d61c7f620e3a9c1389b7b7e334f/doc/easymotion.txt#L942
